### PR TITLE
Correctly handle when a request has no content or content type

### LINKED ISSUE #9: Requests without content result in NullReferenceException
When I added support for signature generation for requests with content in #5 I accidentally removed support for requests without content as they will throw a `NullReferenceException`. 😥

### PR DESCRIPTION
**Pull request by SimonTouchtech**
Fixes #9

### CODE REVIEW

File: src/OAuthMessageHandler.cs [hunk 1]
```diff
@@ -49,7 +49,7 @@ public OAuthMessageHandler(string apiKey, string secret, string authToken, strin
                 queryString = requestUri.Query;
             }
 
-            if (request.Content.Headers.ContentType.MediaType == "application/x-www-form-urlencoded")
+            if (request.Content?.Headers.ContentType?.MediaType == "application/x-www-form-urlencoded")
```
Comment (AlexGhiondea) [inline src/OAuthMessageHandler.cs:52]: Great catch!

**Review by AlexGhiondea — APPROVED** [review]
